<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2018 Cross Solution <http://cross-solution.de>
 */

$this->headTitle('Kontakt');

?>

<h1>Kontakt</h1>

<?php if ($this->sent):?>
<div class="well well-lg">
    <p class="lead">Vielen Dank.</p>
    <p>Ihre Anfrage wurde erfolgreich an uns übermittelt.</p>
</div>
<?php else: ?>
<?=$this->form($this->form)?>
<?php endif ?>


