<?php
/**
 * YAWIK
 * View template of the Login site
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license       MIT
 */
?>
<?php if ($this->required): ?>
    <?php $this->headTitle($this->translate('Login required')); ?>
    <h1><?php echo $this->translate('Please authenticate yourself to proceed') ?></h1>
    <hr />
<?php else: ?>
    <?php $this->headTitle($this->translate('Login')); ?>
    <h1><?php echo $this->translate('Login'); ?></h1>
    <hr />
<?php endif; ?>

<div class="col-md-6 col-md-offset-3" id="yk-login">

    <!-- Tab panes -->

        <div class="panel panel-tabbed tab-pane active" id="login">
            <div class="form-content panel-body">
                <?php echo $this->form($this->loginForm); ?>
                <div class="row">
                    <?php if (!isset($this->allowResetPassword) || $this->allowResetPassword == true): ?>
                        <div class="col-md-6">
                            <a href="<?php echo $this->url('lang/forgot-password'); ?>"
                               title="<?php echo $this->translate('I forgot my password'); ?>" class="small">
                                <?php echo $this->translate('I forgot my password'); ?>
                            </a>
                        </div>
                    <?php endif; ?>
                </div>
                <?php /* if (!isset($this->allowRegister) || $this->allowRegister == true): ?>
                    <?php echo $this->partial('core/social-buttons',[
                            'SocialButtons' => $this->socialButtons(),
                            'alt' => $this->translate('Login with %s'),
                            'label' => $this->translate('Login with ...')]
                    );?>
                <?php endif; */?>
            </div>
        </div>


</div>
