<?php
/** @var \Laminas\View\Renderer\PhpRenderer $this */
/** @var \JobsByMail\Entity\SearchProfileInterface $searchProfile */
$searchProfile = $this->searchProfile;
/** @var \JobsByMail\Service\Hash $hash */
$hash = $this->hash;
$user = $this->user;

// shared vars used in mails
include( __DIR__ . '/' . 'vars.inc.phtml');

?>
<div style="background: #eee;width: 100%;height: 100vh;">
    <div class="size margin-auto"
         style="background-color:<?= $mail_white_color  ?>;max-width:<?=$width?>;width:100%;margin-left: auto;margin-right: auto;">
        <?= $this->partial('mail/header', [
            'title' => 'Kennwort zurücksenden',
            'width'=>$width, 'mail_blue_color'=>$mail_blue_color,
            'mail_white_color' => $mail_white_color]); ?>
        <?=$this->partial('mail/header',[
            'title' => 'Suchprofil bestätigen',
            'width'=>$width
        ])
        ?>

        <p>
            <a href="<?=$this->serverUrl($this->url('lang/jobsbymail/confirm', [
                'id' => $searchProfile->getId(),
                'hash' => $hash->generate($searchProfile)]))?>"><?=$this->translate('Confirm your search profile.')?></a>
        </p>
        <?= $this->partial('mail/footer', ['width'=>$width, 'mail_white_color'=>$mail_white_color]); ?>
    </div>
</div>
