<?php
/**
 * YAWIK
 * Auth Module
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   MIT
 */
/*
 * Sends a mail to the user to reset the password.
 */
/* @var Auth\Entity\Info $user */
$user = $this->user->getInfo();

// shared vars used in mails
include( __DIR__ . '/' . 'vars.inc.phtml');

?>
<div style="background: #eee;width: 100%;height: 100vh;">
    <div class="size margin-auto" style="background-color:<?= $mail_white_color  ?>;max-width:<?=$width?>;width:100%;margin-left: auto;margin-right: auto;">
        <?= $this->partial('mail/header', ['title' => 'Kennwort zurücksenden', 'width'=>$width, 'mail_blue_color'=>$mail_blue_color, 'mail_white_color' => $mail_white_color]); ?>

        <div class="seprate_footer" style="padding:10px;">
            <h3>Hello <?=$user->getLastName(); ?>,</h3>
            <p>
                To assign a new password for applicant management, please click on the following link:
            </p>
            <a style="background-color:<?= $mail_blue_color ?>;padding: 5px 10px 6px 10px;color:<?= $mail_white_color  ?>;text-decoration:none;border-radius:5px;"  href="<?= $this->resetlink; ?>">
                <span style="font-size: 45px;top: 10px;position: relative;">&#8227;</span>
                Confirm link
            </a>
            <p>
                If you have not requested a new password, you do not need to do anything else.
            </p>
            <p>
                Please inform us if you have any concerns about the security of your password.
            </p>
            <?= $this->partial('mail/footer', ['width'=>$width, 'mail_white_color'=>$mail_white_color]); ?>
        </div>
    </div>
</div>