<?php
/**
 * YAWIK
 *
 * @filesource
 * @license    MIT
 * @copyright  2013 - 2015 Cross Solution <http://cross-solution.de>
 */
?>
<?php
/*
 * Available variables:
 * $this->job : The job entity
 * $this->siteName: The site name (from Core/AbstractOptions)
 */

$job = $this->job;
/* @var \Jobs\Entity\Job $job */
$user = $job->getUser();
$info = $user->getInfo();

// shared vars used in mails
include(__DIR__ . '/' . 'vars.inc.phtml');

?>
<div style="background: #eee;width: 100%;height: 100vh;">
    <div class="size margin-auto"
         style="background-color:<?= $mail_white_color ?>;max-width:<?= $width ?>;width:100%;margin-left: auto;margin-right: auto;">
        <?= $this->partial('mail/header', [
                                            'title'            => 'Kennwort zurücksenden',
                                            'width'            => $width,
                                            'mail_blue_color'  => $mail_blue_color,
                                            'mail_white_color' => $mail_white_color
                                        ]
        ); ?>

        <div class="seprate_footer" style="padding:10px;">
            <h3><?php echo 'male' == $info->getGender()
                    ? 'Dear Mr'
                    : 'Dear Mrs' ?> <?php echo $info->getDisplayName(/*emailIfEmpty*/
                    false
                ); ?>,</h3>

            <p>
                Your job opening "<?= $job->getTitle() ?>" referenced by <?= $job->getReference() ?>.
                was rejected.
            </p>

            <p>
                Please correct your job opening
            </p>

            <?= $this->partial('mail/footer', ['width' => $width, 'mail_white_color' => $mail_white_color]); ?>
        </div>
    </div>
</div>