<?php
/**
 * YAWIK
 *
 * @filesource
 * @license    MIT
 * @copyright  2013 - 2015 Cross Solution <http://cross-solution.de>
 */
?>
<?php
/*
 * Available variables:
 * $this->job : The job entity
 * $this->siteName: The site name (from Core/AbstractOptions)
 */

$this->setSubject('Stellenanzeige wurde abgelehnt');

$job = $this->job;
/* @var \Jobs\Entity\Job $job */
$user = $job->getUser();
$info = $user->getInfo();

// shared vars used in mails
include(__DIR__ . '/' . 'vars.inc.phtml');

?>
   <?= $this->partial('mail/header', [
                                            'title'            => 'Stellenanzeige abgelehnt',
                                            'width'            => $width,
                                            'mail_blue_color'  => $mail_blue_color,
                                            'mail_white_color' => $mail_white_color
                                        ]
        ); ?>

 <tr>
	 <td align="center" valign="top">
									<!-- CENTERING TABLE // -->
									<table border="0" cellpadding="0" cellspacing="0" width="100%" bgcolor="#FFF">
										<tbody><tr>
											<td align="center" valign="top">
												<!-- FLEXIBLE CONTAINER // -->
												<table border="0" cellpadding="0" cellspacing="0" width="500" class="flexibleContainer">
													<tbody><tr>
														<td align="center" valign="top" width="500" class="flexibleContainerCell">
															<table border="0" cellpadding="30" cellspacing="0" width="100%">
																<tbody><tr>
																	<td align="center" valign="top">

																		<!-- CONTENT TABLE // -->
																		<table border="0" cellpadding="0" cellspacing="0" width="100%">
																			<tbody><tr>
																				<td valign="top" class="textContent">
																					
<h3 mc:edit="header" style="color:#22436c;line-height:125%;font-family:Helvetica,Arial,sans-serif;font-size:20px;font-weight:bold;margin-top:0;margin-bottom:3px;text-align:left;">
<?php echo 'male' == $info->getGender()
                    ? 'Hallo'
                    : 'Hallo' ?> <?php echo $info->getDisplayName(/*emailIfEmpty*/
                    false
                ); ?></h3>
<div mc:edit="body" style="text-align:left;font-family:Helvetica,Arial,sans-serif;font-size:15px;margin-bottom:0;color:#5F5F5F;line-height:135%;">
 Ihrer Stellenanzeige "<?= $job->getTitle() ?>" <?php if ($job->getReference()): ?>  mit der Referenz <?= $job->getReference() ?><?php endif ?> wurde abgelehnt. Bitte korrigieren Sie Ihre Stellenanzeige.
																					    
																					    </div>
																				</td>
																			</tr>
																		</tbody></table>
																		<!-- // CONTENT TABLE -->

																	</td>
																</tr>
															</tbody></table>
														</td>
													</tr>
												</tbody></table>
												<!-- // FLEXIBLE CONTAINER -->
											</td>
										</tr>
									</tbody></table>
									<!-- // CENTERING TABLE -->
								</td>
							</tr>
				

         <?= $this->partial('mail/footer', ['width' => $width, 'mail_white_color' => $mail_white_color]); ?>
