<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @author        bleek@cross-solution.de
 * @license       MIT
 */
/*
 * Confirmation Mail to the Customer
 */
$job = $this->job;
/* @var \Jobs\Entity\Job $job */
$user = $job->getUser();
$info = $user->getInfo();

// shared vars used in mails
include(__DIR__ . '/' . 'vars.inc.phtml');

?>
<div style="background: #eee;width: 100%;height: 100vh;">
    <div class="size margin-auto"
         style="background-color:<?= $mail_white_color ?>;max-width:<?= $width ?>;width:100%;margin-left: auto;margin-right: auto;">
        <?= $this->partial('mail/header', [
                                            'title'            => 'Kennwort zurücksenden',
                                            'width'            => $width,
                                            'mail_blue_color'  => $mail_blue_color,
                                            'mail_white_color' => $mail_white_color
                                        ]
        ); ?>

        <div class="seprate_footer" style="padding:10px;">
            <h3><?php echo 'male' == $info->getGender()
                    ? 'Dear Mr '
                    : 'Dear Mrs ' ?> <?php echo $info->getDisplayName(/*emailIfEmpty*/
                    false
                ); ?>,</h3>

            <p>
                We hereby acknowledge receipt of your job announcement with the headline <b><?= $job->getTitle() ?></b>
                and the reference <b><?= $job->getReference() ?></b>. You will receive a message as soon as the ad is
                approved and published.
            </p>

            <p>
                You can follow the actual status of your job opening on the <a
                    href="<?php echo $this->serverUrl() . $this->url('lang/jobs', array('lang' => 'de')) ?>">job
                    overview</a>.
            </p>
            <?= $this->partial('mail/footer', ['width' => $width, 'mail_white_color' => $mail_white_color]); ?>
        </div>
    </div>
</div>