<?php
/**
 * YAWIK
 *
 * @filesource
 * @license MIT
 * @copyright  2013 - 2018 Cross Solution <http://cross-solution.de>
 */

/* @var \Core\View\Helper\Proxy\HelperProxy $wp */
$wp = $this->proxy('wordpress');

$this->headTitle($wp->chain(['page' => 586, 'value' => ['title.rendered']], 'Kontakt'));

?>

<h1><?=$wp->call('value', ['title.rendered'])?></h1>

<?php if ($this->sent):?>
<div class="well well-lg">
    <p class="lead">Vielen Dank.</p>
    <p>Ihre Anfrage wurde erfolgreich an uns übermittelt.</p>
</div>
<?php else: ?>
    <div class="container">
        <?=$wp->call('value', ['content.rendered'])?>
    </div>
    <hr>
    <div class="container">
        <?=$this->form($this->form)?>
    </div>
<?php endif ?>


