<?php
/**
 * Gastrojobs24
 *
 * General layout template file. Defines the general layout.
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   Gastrojobs
 */

/* @var $options \Core\Options\ModuleOptions */
$options = $this->services('Core/Options');
$lang = $this->params('lang');

// See: http://yawik.readthedocs.org/en/latest/modules/core/notifications.html

$notifications = $this->partial('core/notifications');

// set default page title

$this->headTitle($this->translate('Vertriebskarriere.com'))->setSeparator(' | ')->setAutoEscape(false);

// set default keywords

$this->headMeta()->setCharset("utf-8");
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');

$this->configHeadScript()->prependScript('var lang="' . $lang . '";'
                                         . 'var basePath="' . $this->basePath() . '";');

$this->headLink()->prependStylesheet($this->basePath() . '/modules/JobsFrankfurt/layout.css');
$this->headLink()->prependStylesheet($this->basePath('dist/css/core.min.css'));
$this->configHeadScript()->prependFile($this->basepath('dist/js/core.js'));
$this->configHeadScript()->appendFile($this->basePath('modules/JobsFrankfurt/dist/vertriebskarriere.js'));

$langScript = 'dist/locales/' . $lang . '.js';
$this->configHeadScript()->appendFile($this->basePath($langScript));

$this->configHeadScript()->appendScript('var lang="' . $this->params('lang') . '";'
    . 'var basePath="' . $this->basePath() . '";');

?>
<?= $this->doctype(); ?>
<html lang="<?php echo $this->params('lang') ?>">
<head>
    <?= $this->headTitle() ?>
    <?= $this->headMeta() ?>
    <?= $this->configHeadScript() ?>
    <?= $this->headLink() ?>
    <?= $this->headStyle() ?>
    <script>
        (function( $ ) {
	'use strict';

    /**
     * FAQs Toggles
     */
    $(function() {
        $('.qe-toggle-title').click(function () {
            var parent_toggle = $(this).closest('.qe-faq-toggle');
            if ( parent_toggle.hasClass( 'active' ) ) {
                $(this).find('i.fa').removeClass( 'fa-minus-circle' ).addClass( 'fa-plus-circle' );
                parent_toggle.removeClass( 'active' ).find( '.qe-toggle-content' ).slideUp( 'fast' );
            } else {
                $(this).find('i.fa').removeClass( 'fa-plus-circle' ).addClass( 'fa-minus-circle' );
                parent_toggle.addClass( 'active' ).find( '.qe-toggle-content' ).slideDown( 'fast' );
            }
        });
    });

    /**
     * FAQs Filter
     */
    $(function() {
        $('.qe-faqs-filter').click( function ( event ) {
            event.preventDefault();
            $(this).parents('li').addClass('active').siblings().removeClass('active');
            var filterSelector = $(this).attr( 'data-filter' );
            var allFAQs = $( '.qe-faq-toggle' );
            if ( filterSelector == '*' ) {
                allFAQs.show();
            } else {
                allFAQs.not( filterSelector ).hide().end().filter( filterSelector ).show();
            }
        });
    });

})( jQuery );
    </script>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800&display=swap" rel="stylesheet">

</head>
<body>
<?php if (!$this->noHeader):?>
    <header id="header" role="banner">
          <div class="navbar">
		     <div class="row">
               <div class="navbar-header">
                  <button class="navbar-toggle collapsed" data-target="#main-navigation" data-toggle="collapse" type="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <div class="logo">
                      <div class="logo-animated">                  
                      <svg viewBox="-5 -5 8 8">
                            <circle cx="0" cy="0" r="3" fill="#dae8fc" opacity="0.5">
                                <animateTransform attributeName="transform" type="scale" additive="sum" from="0 0" to="1 1" begin="0s" dur="0.8s" repeatCount="1"></animateTransform>
                            </circle>
                        </svg>
                        <div class="move">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="95px" height="82px" viewBox="-0.5 -0.5 95 82">
                                <defs/>
                                <g>
                                    <path d="M 20 74 Q 55 59 87.52 18.35" fill="none" stroke="#fff" stroke-width="4" stroke-miterlimit="10" pointer-events="stroke"/>
                                    <path d="M 92.21 12.49 L 89.86 23.42 L 87.52 18.35 L 82.06 17.18 Z" fill="#fff" stroke="#fff" stroke-width="4" stroke-miterlimit="10" pointer-events="all"/>
                                </g>
                            </svg>
                        </div>
                                <div class="bar01"></div>
                                <div class="bar02"></div>
                                <div class="bar03"></div>
                                <div class="bar04 clearfix"></div>
                            </div>                          
                        </div>                      
                    <div class="logotype"><a href="/de"><span>Vertriebs</span>karriere</a></div>
                  </div>            
            
                <nav id="main-navigation" class="navbar-collapse collapse navbar-collapse" role="navigation">


                <?= $this->loginInfo(array('lang' => $lang ));?>
                <?= $this->navigation('Core/Navigation')
                         ->setAcl($this->services('acl'))
                         ->setRole($this->auth('role'))
                         ->menu()
                         ->setMaxDepth(0) // only show the top level entries
                         ->renderPartial(null, 'main-navigation');
//                         ->setUlClass('nav navbar-nav pull-right')//renderPartial(null, 'main-navigation')
                ?>

            </nav>
            </div>
            <!-- /main-navigation -->
        </div>
     </div>
        <div id="formular">
        </div>
    </header>
    <?php endif ?>
 <style>

     #content .navbar {

         position:static!important;

     }


 </style>

<main id="content">
        <?php echo $notifications?>
         <?php echo $this->content;?>
</main>

<?php if (!$this->noFooter): echo $this->partial("footer"); endif; ?>
<script>
  new cookieNoticeJS({

    // Localizations of the notice message
    'messageLocales': {
      'it': 'Custom localized message'
    },

    // Localizations of the dismiss button text
    'buttonLocales': {
      'it': 'Chiudi'
    },

    // Shows the "learn more button (default=false)
    'learnMoreLinkEnabled': false,

    // The message will be shown again in X days
    'expiresIn': 30,

    // Dismiss button background color
    'buttonBgColor': '#d35400',

    // Dismiss button text color
    'buttonTextColor': '#fff',

    // Notice background color
    'noticeBgColor': '#000',

    // Notice text color
    'noticeTextColor': '#fff',

    // the learnMoreLink color (default='#009fdd')
    'linkColor': '#f00',

    // The target of the learn more link (default='', or '_blank')
    'linkTarget': '',

    // Print debug output to the console (default=false)
    'debug': false
  });
</script>

</body>
</html>
