<?php
/**
 * Gastrojobs24
 *
 * General layout template file. Defines the general layout.
 *
 * @copyright (c) 2013 - 2016 Cross Solution (http://cross-solution.de)
 * @license   Gastrojobs
 */

/* @var $options \Core\Options\ModuleOptions */
$options = $this->services('Core/Options');
$lang = $this->params('lang');

// See: http://yawik.readthedocs.org/en/latest/modules/core/notifications.html

$notifications = $this->partial('core/notifications');

// set default page title

$this->headTitle($this->translate('Vertriebskarriere.com'))->setSeparator(' | ')->setAutoEscape(false);

// set default keywords

$this->headMeta()->setCharset("utf-8");
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');

$this->configHeadScript()->prependScript('var lang="' . $lang . '";'
                                         . 'var basePath="' . $this->basePath() . '";');

$this->headLink()->prependStylesheet($this->basePath() . '/modules/JobsFrankfurt/layout.css');
$this->headLink()->prependStylesheet($this->basePath('dist/css/core.min.css'));
$this->configHeadScript()->prependFile($this->basepath('dist/js/core.js'));
$this->configHeadScript()->appendFile($this->basePath('modules/JobsFrankfurt/dist/vertriebskarriere.js'));

$langScript = 'dist/locales/' . $lang . '.js';
$this->configHeadScript()->appendFile($this->basePath($langScript));

$this->configHeadScript()->appendScript('var lang="' . $this->params('lang') . '";'
    . 'var basePath="' . $this->basePath() . '";');

?>
<?= $this->doctype(); ?>
<html lang="<?php echo $this->params('lang') ?>">
<head>
    <?= $this->headTitle() ?>
    <?= $this->headMeta() ?>
    <?= $this->configHeadScript() ?>
    <?= $this->headLink() ?>
    <?= $this->headStyle() ?>
    <script>
        (function( $ ) {
	'use strict';

    /**
     * FAQs Toggles
     */
    $(function() {
        $('.qe-toggle-title').click(function () {
            var parent_toggle = $(this).closest('.qe-faq-toggle');
            if ( parent_toggle.hasClass( 'active' ) ) {
                $(this).find('i.fa').removeClass( 'fa-minus-circle' ).addClass( 'fa-plus-circle' );
                parent_toggle.removeClass( 'active' ).find( '.qe-toggle-content' ).slideUp( 'fast' );
            } else {
                $(this).find('i.fa').removeClass( 'fa-plus-circle' ).addClass( 'fa-minus-circle' );
                parent_toggle.addClass( 'active' ).find( '.qe-toggle-content' ).slideDown( 'fast' );
            }
        });
    });

    /**
     * FAQs Filter
     */
    $(function() {
        $('.qe-faqs-filter').click( function ( event ) {
            event.preventDefault();
            $(this).parents('li').addClass('active').siblings().removeClass('active');
            var filterSelector = $(this).attr( 'data-filter' );
            var allFAQs = $( '.qe-faq-toggle' );
            if ( filterSelector == '*' ) {
                allFAQs.show();
            } else {
                allFAQs.not( filterSelector ).hide().end().filter( filterSelector ).show();
            }
        });
    });

})( jQuery );
    </script>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800&display=swap" rel="stylesheet">

</head>
<body>
<?php if (!$this->noHeader):?>
    <header id="header" role="banner">
          <div class="navbar">
		     <div class="row">
               <div class="navbar-header">
                 <button class="navbar-toggle collapsed" data-target="#main-navigation" data-toggle="collapse" type="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <div class="logo">
                    <a href="/de">
                        <img src="<?php echo $this->basepath('/modules/JobsFrankfurt/logo_icon.png') ?>" alt="Vertriebskarriere">
                    </a>
                  </div>
                  <div class="logotype"><span>Vertriebs</span>karriere</div>
                </div>
            
            <nav id="main-navigation" class="navbar-collapse collapse navbar-collapse" role="navigation">


                <?= $this->loginInfo(array('lang' => $lang ));?>
                <?= $this->navigation('Core/Navigation')
                         ->setAcl($this->services('acl'))
                         ->setRole($this->auth('role'))
                         ->menu()
                         ->setMaxDepth(0) // only show the top level entries
                         ->renderPartial(null, 'main-navigation');
//                         ->setUlClass('nav navbar-nav pull-right')//renderPartial(null, 'main-navigation')
                ?>

            </nav>
            </div>
            <!-- /main-navigation -->
        </div>
     </div>
        <div id="formular">
        </div>
    </header>
    <?php endif ?>
 <style>

     #content .navbar {

         position:static!important;

     }


 </style>

<main id="content">
        <?php echo $notifications?>
         <?php echo $this->content;?>
</main>

<?php if (!$this->noFooter): echo $this->partial("footer"); endif; ?>
<script>
  new cookieNoticeJS({

    // Localizations of the notice message
    'messageLocales': {
      'it': 'Custom localized message'
    },

    // Localizations of the dismiss button text
    'buttonLocales': {
      'it': 'Chiudi'
    },

    // Shows the "learn more button (default=false)
    'learnMoreLinkEnabled': false,

    // The message will be shown again in X days
    'expiresIn': 30,

    // Dismiss button background color
    'buttonBgColor': '#d35400',

    // Dismiss button text color
    'buttonTextColor': '#fff',

    // Notice background color
    'noticeBgColor': '#000',

    // Notice text color
    'noticeTextColor': '#fff',

    // the learnMoreLink color (default='#009fdd')
    'linkColor': '#f00',

    // The target of the learn more link (default='', or '_blank')
    'linkTarget': '',

    // Print debug output to the console (default=false)
    'debug': false
  });
</script>

</body>
</html>
